services:
  api-gateway:
    restart: always
    build: ./api-gateway
    ports:
      - "8000:80"
    depends_on:
      - plc_data_service
      - item_checker_service
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config  # монтирование конфигурационного файла
      - ./mosquitto/data:/mosquitto/data  # монтирование данных
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network


  plc_data_service:
    restart: always
    build:
      context: .
      dockerfile: services/plc_data_hub/Dockerfile
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

  item_checker_service:
    build:
      context: .
      dockerfile: services/item_checker/Dockerfile
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

  hmi_statistic_service:
    build:
      context: .
      dockerfile: services/hmi_statistic/Dockerfile
    volumes:
      - ./shared:/app/shared
    depends_on:
      mosquitto:
        condition: service_healthy
    networks:
      - app-network

  api:
    container_name: manufactory_api
    restart: always
    build: .
    ports:
      - "7000:7000"
    networks:
      - default


networks:
  default:
    name: docker_network
    external: true
  app-network:
    driver: bridge
