version: '3.8'

services:
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - "7000:80"
#    depends_on:
#      - plc_data_service
#      - plc_alarm_service
#      - print_service
#      - telegram_bot_service
#    networks:
#      - app-network

  api:
    container_name: manufactory_api
    restart: always
    build: .
    ports:
      - "7000:7000"
    networks:
      - default

  plc_data_service:
    build: ./services/plc_data_service
    restart: always
    networks:
      - app-network


networks:
  default:
    name: docker_network
    external: true
  app-network:
    driver: bridge
