version: '3.8'

services:
  API:
    container_name: API
    restart: always
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./logs:/scr/logs


networks:
  default:
    name: docker_network
    external: true
