services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:80"
    depends_on:
      - plc_data_service
    networks:
      - app-network

  plc_data_service:
    build: services/plc_hub_service
    networks:
      - app-network
  api:
    container_name: manufactory_api
    restart: always
    build: .
    ports:
      - "7000:7000"
    networks:
      - default




networks:
  default:
    name: docker_network
    external: true
  app-network:
    driver: bridge
