version: '3.8'

services:
  api:
    container_name: manufactory_api
    restart: always
    build: .
    ports:
      - "7000:7000"
    networks:
      - default

  frontend:
    container_name: manufactory_frontend
    build:
      context: ./src/frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"  # Frontend будет доступен на 3000 порту
    networks:
      - default

networks:
  default:
    name: docker_network
    external: true
