"""Add sensor_histories relationship to Place

Revision ID: 508218d45c1e
Revises: d057ed6c6039
Create Date: 2024-12-27 14:27:13.011340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "508218d45c1e"
down_revision: Union[str, None] = "d057ed6c6039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
