"""Add unique constraint to sensor name

Revision ID: 5b26d49a21f8
Revises: 9990467dfa7e
Create Date: 2025-01-08 00:05:48.226736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b26d49a21f8"
down_revision: Union[str, None] = "9990467dfa7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_sensor_name", "sensor", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_sensor_name", "sensor", type_="unique")
    # ### end Alembic commands ###
