"""fix tables

Revision ID: d057ed6c6039
Revises: 6e532912dad1
Create Date: 2024-12-26 17:07:43.402985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d057ed6c6039"
down_revision: Union[str, None] = "6e532912dad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm_tag",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_table(
        "place",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("message_thread_id", sa.String(length=100), nullable=False),
        sa.Column("ip", sa.String(length=39), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sensor",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alarm_message",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["alarm_tag.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message"),
    )
    op.create_table(
        "operations_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=True),
        sa.Column("program", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("dt_created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sensor_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("dt_created", sa.DateTime(), nullable=False),
        sa.Column("place_id", sa.BigInteger(), nullable=False),
        sa.Column("sensor_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"], ["place.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensor.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alarm_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("place_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("additional_data", sa.String(length=500), nullable=True),
        sa.Column("dt_created", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["alarm_message.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["place.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alarm_history")
    op.drop_table("sensor_history")
    op.drop_table("operations_history")
    op.drop_table("alarm_message")
    op.drop_table("sensor")
    op.drop_table("place")
    op.drop_table("alarm_tag")
    # ### end Alembic commands ###
